**veri analizi**

**numpy**

In [1]:
import numpy as np

In [2]:
liste=[6,8,7,9,8]
type(liste)

list

In [3]:
npArr=np.array(liste)
type(npArr)

numpy.ndarray

In [4]:
np.arange(4)

array([0, 1, 2, 3])

In [5]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.empty(5)

array([1.04316289e-311, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000])

In [9]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.linspace(0,10,5,dtype = int)

array([ 0,  2,  5,  7, 10])

In [11]:
d1=[1,2,3,]
d2=[4,5,6]
print(d1*d2)

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
d1=np.array(d1)
d2=np.array(d2)
print(d1*d2)

[ 4 10 18]


In [14]:
arr=np.array([2,1,5,8,9,7])
np.append(arr,9)

array([2, 1, 5, 8, 9, 7, 9])

In [15]:
np.insert(arr,0,12)

array([12,  2,  1,  5,  8,  9,  7])

In [16]:
arr=np.array([2,1,5,8,9,7])

In [17]:
np.delete(arr,2)

array([2, 1, 8, 9, 7])

In [19]:
np.delete(arr,np.where(arr==7))

array([2, 1, 5, 8, 9])

In [20]:
arr=np.array([2,1,5,8,9,7])
np.sort(arr)

array([1, 2, 5, 7, 8, 9])

In [21]:
a=np.array([1,5,8,])
b=np.array([7,7,5,])
np.concatenate((a,b))

array([1, 5, 8, 7, 7, 5])

In [23]:
x=np.array([[1,2],
          [3,4]])
y=np.array([[5,6],
          [7,8]])
np.concatenate((x,y),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [24]:
x=np.array([[1,2],
          [3,4]])
np.hstack(x,[[5,6],
          [7,8]])

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [27]:
arr=np.array([[1,2,3,4,5,6],
             [5,8,7,82,],
            [4,8,9,7,2]])
arr.ndim

C:\Users\HaSaN\AppData\Local\Temp\ipykernel_3176\4135098025.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1,2,3,4,5,6],


1

In [28]:
arr.size

3

In [30]:
arr.shape

(3,)

In [31]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [33]:
b=a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
data=np.array([1,2,3])
data[1]

2

In [35]:
data[0:2]

array([1, 2])

In [36]:
arr[1]

[5, 8, 7, 82]

In [37]:
arr[0:2]

array([list([1, 2, 3, 4, 5, 6]), list([5, 8, 7, 82])], dtype=object)

In [38]:
arr[0:2,1:3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [40]:
import pandas as pd
data=pd.DataFrame({"sehirler":["malatya","yozgat","istanbul"],
                      "plakalar":[44,66,34],
                  "ilceler":["battalgazi","sorgun","ese"]})

In [41]:
data

sehirler  plakalar     ilceler
0   malatya        44  battalgazi
1    yozgat        66      sorgun
2  istanbul        34         ese

In [51]:
print("sehirler"," ","plakalar","  ","ilceler")
a=0
for i in range(3):
    print(i,"malatya","   ",44,"   ","battalgazi")
    
    

sehirler   plakalar    ilceler
0 malatya     44     battalgazi
1 malatya     44     battalgazi
2 malatya     44     battalgazi
